name: books_finder
description: A library to help on the search for books on google books api
version: 3.1.0
repository: https://github.com/bdlukaa/books_finder

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  http: ^0.13.0
